name: example
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  swc_flutter:
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  swc_flutter:
    path: ../

flutter:
  uses-material-design: true